name: chuvas_de_ofertas
description: "Aplicativo para comparar ofertas de supermercados."
publish_to: 'none' # Use 'none' para projetos privados

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/offers.json
